### PR TITLE
REPL

### PR DESCRIPTION
**Pull request by parkan**
Ok, I think this is more or less in a working place, ready for review.

### CODE REVIEW

**Comment by yusefnapora** [comment]
I figured out how to make the repl promise wrapper support assigning the resolved value of a promise to a var.  so you can do e.g. `var result = node.remoteQuery('SELECT * FROM foo')` and it will block until the query completes and assign the result to `result`.  It's a pretty ugly hack, but it works...

I can't decide 100% if it's a good idea though, since sometimes you may want to assign the actual Promise object to the var instead.  I could pretty easily hack in support for the `await` keyword, so that you'd have to do `var result = await someAsyncOp()` instead.  

Or we could just not bother, and if you want to store the result in a var you can wait for the operation to complete and do `var result = _`, since the last evaluation is stored in the magic `_` variable.

It is nice being able to block during an assignment operation though and the `_` trick isn't very discoverable, so I kind of want to add it.  Anyway, open to suggestions :)

**Comment by parkan** [comment]
Thinking through the API here. 

These make sense:

```js
remote.ping
remote.remoteQuery // or even remote.query
remote.remoteData // or even remote.data
```

Eventually we'll want helpers for stuff like
* push publishing
* creating additional remotes
* remote-to-remote merge

But this seems like it should be enough for the moment

Thoughts on promise handling: basically I think awaiting by default is good enough if we can still get async evaluation with directly chaining calls with `then` (and maybe even without that). Overall, the semantics of async/background operations in the REPL don't really make much sense to me

**Comment by parkan** [comment]
Other option is to define them as _commands_:

```js
remoteQuery(...)
remoteData(...)
```

though ping makes less sense then

**Comment by yusefnapora** [comment]
This looks good to me; I think we should pull it in.  I miss it when I'm working on a different branch :)

**Pull request merged**
